### ISSUE TITLE
Nav element in layout does not properly close

### ISSUE THREAD

**Issue by biscuitvile** [KarKimYong/website#2]
If you look at the `nav` element in the layout (https://github.com/KarKimYong/website/blob/master/views/layout.erb#L16-L25)

You will see that the element does not properly close and that there are two open tags instead of an opening and closing pair of `<nav>` and `</nav>`.

**Comment by KarKimYong** [comment]
[image: image.png]

**Comment by KarKimYong** [comment]
fixed
